apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Twitter calls UMS via Kubernetes Service DNS
  UMS_HOST: "http://ums"
  UMS_PORT: "8081"
  TWITTER_PORT: "8082"

  # DB URLs
  UMS_JDBC_URL: "jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  TWITTER_JDBC_URL: "jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_USERNAME: "appuser"
  DB_PASSWORD: "apppass"
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  JWT_SECRET: "secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: ums-oauth-secret
type: Opaque
stringData:
  GITHUB_CLIENT_ID: "Ov23lijRIy7eyahBQs7n"
  GITHUB_CLIENT_SECRET: "3996e1a8aace9e8810012f0e786f6699d1541622"
